### ISSUE TITLE
callout box images need lighter background color

### ISSUE THREAD

**Issue by kanarb** [knice/ucsc-drupal#41]
Example:

http://website.library.ucsc.edu/find/find-books

**Comment by knice** [comment]
Images in callout boxes aren't supposed to have a background color at all. The padding is set to 0, so there should be no visible background color. 

I forgot to include the `callout-full` class in the style rule that resets images in callouts. I have corrected that.

So, I changed:

``` css
.callout-left img,
.callout-right img {
  margin:0; 
  padding:0;
}
```

to 

``` css
.callout-full img,
.callout-left img,
.callout-right img {
  margin:0; 
  padding:0;
}
```
